### ISSUE TITLE
Add a working config file

### ISSUE THREAD

**Issue by cg0** [Reddy360/Dragon-Power#1]
A configuration file would allow the plugin to be fully customisable without editing the source code, so even a Ffaen could do it

**Comment by Reddy360** [comment]
Config values done:

* logAPICalls
* fireDragon.enabled
* fireDragon
* fireDragon
* fireDragon

**Comment by cg0** [comment]
Added in 35472240194f563991a318bb3f9ee45cbe154f46

Closing issue.
